server:
  port: 8080

spring:
  application:
    name: video-process
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  endpoint: http://yzt.local:9000
  access-key: Zw9EbInxAdaNdC4rTfTo
  secret-key: JpGXiOOfsSlz2nfNcfsZmgF1ySAJdSfSSfHS7F0i
  bucket-name: yzt

ffmpeg:
  path: ${FFMPEG_PATH:ffmpeg}
  ffprobe-path: ${FFPROBE_PATH:ffprobe}
